-- Agregar columnas para pack 4 y pack 5
ALTER TABLE sorteos
ADD COLUMN IF NOT EXISTS cantidad_pack_4 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS precio_pack_4 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pack_4_visible BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS descripcion_pack_4 TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS cantidad_pack_5 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS precio_pack_5 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pack_5_visible BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS descripcion_pack_5 TEXT DEFAULT '';
